### ISSUE TITLE
when i run flask run -p 8000, some issues occurred

### ISSUE THREAD

**Issue by Xinyi118** [xlang-ai/OpenAgents#104]
(openagents) root@DataAgent:~/OpenAgents-main/backend# flask run -p 8000
 * Serving Flask app 'main.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'backend.main', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/root/OpenAgents-main/backend/__init__.py", line 4, in <module>
    from backend.api import (
  File "/root/OpenAgents-main/backend/api/chat_copilot.py", line 5, in <module>
    from backend.api.file import _get_file_path_from_node
  File "/root/OpenAgents-main/backend/api/file.py", line 7, in <module>
    from backend.app import app
  File "/root/OpenAgents-main/backend/app.py", line 4, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'

**Comment by Xinyi118** [comment]
> It seems like you don't have flask in your computer. Did you set up the environment?

**Comment by Xinyi118** [comment]
change OS from Centos to Ubuntu, solved

**Comment by Xinyi118** [comment]
change OS from Centos to Ubuntu, solved, tks
