### ISSUE TITLE
Issue with npm install

### ISSUE THREAD

**Issue by Collin-Budrick** [xlang-ai/OpenAgents#22]
Hi, I attempted to install the frontend of Open Agents on my Raspberry Pi 4. I have already installed the backend, successfully for the most part. 

Node and npm versions:
```
$ node -v
v9.9.0
$ npm -v
5.6.0
```
Here are the system details:
```
OS: Ubuntu 20.04.6 LTS aarch64
Host: Raspberry Pi 4 Model B Rev 1.1
Kernel: 5.4.0-1095-raspi
Packages: 648 (dpkg), 4 (snap)
Shell: bash 5.0.17
CPU: BCM2835 (4) @ 1.500GHz
Memory: 180MiB / 3791MiB
```

When running from the frontend directory like so: ``$ me@OpenAgent:/home/quantum7/OpenAgents/frontend# npm install``
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> esbuild@0.17.14 postinstall /home/quantum7/OpenAgents/frontend/node_modules/esbuild
> node install.js

/home/quantum7/OpenAgents/frontend/node_modules/esbuild/install.js:117
      } catch {
              ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    
npm WARN @mui/x-date-pickers@6.4.0 requires a peer of date-fns@^2.25.0 but none is installed. You must install peer dependencies yourself.
npm WARN @mui/x-date-pickers@6.4.0 requires a peer of date-fns-jalali@^2.13.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @mui/x-date-pickers@6.4.0 requires a peer of luxon@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @mui/x-date-pickers@6.4.0 requires a peer of moment-hijri@^2.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN @mui/x-date-pickers@6.4.0 requires a peer of moment-jalaali@^0.7.4 || ^0.8.0 || ^0.9.0 || ^0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@4.11.3 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/styles@4.11.5 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/system@4.12.2 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/utils@4.11.3 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@17.0.2 requires a peer of react@17.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@21.1.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@13.2.4 requires a peer of @opentelemetry/api@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@13.2.4 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@13.2.4 requires a peer of node-sass@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@13.2.4 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN node-fetch@2.6.9 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN pdfjs-dist@2.16.105 requires a peer of worker-loader@^3.0.8 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-load-config@3.1.4 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of @ianvs/prettier-plugin-sort-imports@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of @prettier/plugin-php@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of @prettier/plugin-pug@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of @shopify/prettier-plugin-liquid@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of @shufo/prettier-plugin-blade@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of @trivago/prettier-plugin-sort-imports@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-astro@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-css-order@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-import-sort@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-jsdoc@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-organize-attributes@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-organize-imports@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-style-order@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-svelte@* but none is installed. You must install peer dependencies yourself.
npm WARN prettier-plugin-tailwindcss@0.2.5 requires a peer of prettier-plugin-twig-melody@* but none is installed. You must install peer dependencies yourself.
npm WARN rc-picker@3.7.6 requires a peer of date-fns@>= 2.x but none is installed. You must install peer dependencies yourself.
npm WARN rc-picker@3.7.6 requires a peer of luxon@>= 3.x but none is installed. You must install peer dependencies yourself.
npm WARN react-pdf@6.2.2 requires a peer of file-loader@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@7.2.4 requires a peer of react@^16.8.3 || ^17 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@18.1.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.13.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.13.0 requires a peer of utf-8-validate@>=5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-x64@0.17.14 (node_modules/@esbuild/linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-x64@0.17.14: wanted {"os":"linux","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm-eabi@13.2.4 (node_modules/@next/swc-android-arm-eabi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm-eabi@13.2.4: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm64@13.2.4 (node_modules/@next/swc-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm64@13.2.4: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@13.2.4 (node_modules/@next/swc-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@13.2.4: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@13.2.4 (node_modules/@next/swc-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@13.2.4: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-freebsd-x64@13.2.4 (node_modules/@next/swc-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-freebsd-x64@13.2.4: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm-gnueabihf@13.2.4 (node_modules/@next/swc-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm-gnueabihf@13.2.4: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-gnu@13.2.4 (node_modules/@next/swc-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-gnu@13.2.4: wanted {"os":"linux","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-musl@13.2.4 (node_modules/@next/swc-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-musl@13.2.4: wanted {"os":"linux","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@13.2.4 (node_modules/@next/swc-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@13.2.4: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@13.2.4 (node_modules/@next/swc-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@13.2.4: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@13.2.4 (node_modules/@next/swc-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@13.2.4: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.17.14 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esbuild@0.17.14 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-10-24T23_27_43_978Z-debug.log
```

I don't think this would be an arm related issue according to the log above, but I could be wrong:
```
467 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
467 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
467 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
467 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64
```

I have tried installing it from root account just to see if it was a permissions issue, but same result. I am running an x64 OS.

Any help would be very appreciated in pointing me in the right direction. Thanks!

**Comment by WhiteWolf82** [comment]
Hi, can you try updating your node and npm versions? e.g. node 18.7.0 and npm 8.15.0, as the lockfileVersion issue is usually related to npm versions.
