### ISSUE TITLE
python3.11 supported

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [xlang-ai/OpenAgents#24]
The running background reported an error, the initial interpretation is compatible with Python3.11, the error is as follows:

flask run -p 8000
Traceback (most recent call last):
  File "/opt/homebrew/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/opt/homebrew/lib/python3.11/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/raoyunfei/OpenAgents/backend/__init__.py", line 4, in <module>
    from backend.api import (
  File "/Users/raoyunfei/OpenAgents/backend/api/chat_copilot.py", line 5, in <module>
    from backend.api.file import _get_file_path_from_node
  File "/Users/raoyunfei/OpenAgents/backend/api/file.py", line 8, in <module>
    from backend.main import (
  File "/Users/raoyunfei/OpenAgents/backend/main.py", line 6, in <module>
    from backend.kernel_publisher import start_kernel_publisher
  File "/Users/raoyunfei/OpenAgents/backend/kernel_publisher.py", line 4, in <module>
    from backend.utils.utils import logger
  File "/Users/raoyunfei/OpenAgents/backend/utils/utils.py", line 14, in <module>
    from real_agents.adapters.data_model import (
  File "/Users/raoyunfei/OpenAgents/real_agents/adapters/data_model/__init__.py", line 2, in <module>
    from real_agents.adapters.data_model.database import DatabaseDataModel
  File "/Users/raoyunfei/OpenAgents/real_agents/adapters/data_model/database.py", line 10, in <module>
    from real_agents.adapters.data_model.table import TableDataModel
  File "/Users/raoyunfei/OpenAgents/real_agents/adapters/data_model/table.py", line 9, in <module>
    from real_agents.adapters.data_model.templates.skg_templates.table_templates import serialize_df
  File "/Users/raoyunfei/OpenAgents/real_agents/adapters/data_model/templates/skg_templates/table_templates.py", line 10, in <module>
    from real_agents.adapters.schema import SQLDatabase
  File "/Users/raoyunfei/OpenAgents/real_agents/adapters/schema.py", line 2, in <module>
    from langchain import SQLDatabase
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/tools/__init__.py", line 26, in <module>
    from langchain.tools.openapi.utils.api_models import APIOperation
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/tools/openapi/utils/api_models.py", line 6, in <module>
    from openapi_schema_pydantic import MediaType, Parameter, Reference, RequestBody, Schema
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/__init__.py", line 3, in <module>
    from .v3 import *
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/__init__.py", line 1, in <module>
    from .v3_1_0 import *
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/__init__.py", line 9, in <module>
    from .open_api import OpenAPI
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/open_api.py", line 5, in <module>
    from .components import Components
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/components.py", line 7, in <module>
    from .header import Header
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/header.py", line 3, in <module>
    from .parameter import Parameter
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/parameter.py", line 6, in <module>
    from .media_type import MediaType
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/media_type.py", line 8, in <module>
    from .schema import Schema
  File "/opt/homebrew/lib/python3.11/site-packages/openapi_schema_pydantic/v3/v3_1_0/schema.py", line 10, in <module>
    class Schema(BaseModel):
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 2725, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name

**Comment by BlankCheng** [comment]
Hi, thanks for your feedback. I've searched for pydantic + python 3.11 and it seems it's a common conflict. 
I found a solution https://github.com/freqtrade/freqtrade/issues/7541 here, can you try it and tell us if that can work?
Thank you!

**Comment by shanmu-raoyunfei** [comment]
resolved，thks
