### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [xlang-ai/OpenAgents#35]
An error occurred while executing “npm run dev”：

⨯ TypeError: Cannot read properties of undefined (reading 'includes')
    at get platform [as platform] (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4222:23)
    at new KeyboardManager (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4202:35)
    at <static_initializer> (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4369:29)
    at Object.defineProperty.value (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4342:22)
    at __w_pdfjs_require__ (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at Object.defineProperty.value (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:3737:14)
    at __w_pdfjs_require__ (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at Object.defineProperty.value (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:3562:15)
    at __w_pdfjs_require__ (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at Object.defineProperty.value (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:1119:27)
    at __w_pdfjs_require__ (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at /Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19718:12
    at /Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19767:3
    at /Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19770:12
    at webpackUniversalModuleDefinition (/Users/raoyunfei/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:25:20) {
  page: '/'

node：v21.1.0
npm：10.2.0

The initial suspicion is the version of “node” and “npm”, then what is the correct version。

thks

**Comment by BlankCheng** [comment]
It seems an error of mismatched npm versions for pdfjs-dist. Maybe you can find some related issues in https://github.com/mozilla/pdf.js. 
Fyi, my local setup is Node.js v21.0.0, npm 10.2.0, and the `npm run dev` works.

**Comment by BlankCheng** [comment]
Closed as it suspends for long. Pls reopen if you have any question.
