### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [xlang-ai/OpenAgents#58]
npm run error：

> ai-chatbot-starter@0.1.0 dev
> next dev

(node:54255) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:54256) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 2.1s (273 modules)
wait  - compiling...
event - compiled successfully in 104 ms (235 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 13.7s (20963 modules)
wait  - compiling /_error (client and server)...
error - ReferenceError: window is not defined
    at detect (/Users/raoyunfei/OpenAgents/frontend/node_modules/echarts/dist/echarts.js:123:54)
    at /Users/raoyunfei/OpenAgents/frontend/node_modules/echarts/dist/echarts.js:97:9
    at /Users/raoyunfei/OpenAgents/frontend/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/Users/raoyunfei/OpenAgents/frontend/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.echarts (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:1391:18)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Datatype/Chart/Echart.tsx:9:65)
    at ./components/Datatype/Chart/Echart.tsx (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:491:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Chat/ChatRichContentItem.tsx:15:91)
    at __webpack_require__.a (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/Chat/ChatRichContentItem.tsx:1:21)
    at ./components/Chat/ChatRichContentItem.tsx (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:293:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Chat/ChatMessage.tsx:16:94)
    at __webpack_require__.a (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/Chat/ChatMessage.tsx:1:21)
    at ./components/Chat/ChatMessage.tsx (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:282:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Chat/Chat.tsx:18:70)
    at __webpack_require__.a (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/Chat/Chat.tsx:1:21)
    at ./components/Chat/Chat.tsx (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:249:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/api/home/home.tsx:41:80)
    at __webpack_require__.a (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/api/home/home.tsx:1:21)
    at ./pages/api/home/home.tsx (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:722:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/api/home/index.ts:7:63)
    at __webpack_require__.a (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/api/home/index.ts:1:21)
    at ./pages/api/home/index.ts (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:733:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:7:67)
    at __webpack_require__.a (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/index.tsx:1:21)
    at ./pages/index.tsx (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:744:1)
    at __webpack_require__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:1764:39)
    at /Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:1765:28
    at Object.<anonymous> (/Users/raoyunfei/OpenAgents/frontend/.next/server/pages/index.js:1768:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
  page: '/zh'
}
event - compiled client and server successfully in 1583 ms (20964 modules)

**Comment by miandai** [comment]
Encountered the same problem. 

The front-end has never been successfully deployed and there are always various issues.

It's very frustrating.

**Comment by BlankCheng** [comment]
Closed as inactive. Please feel free to reopen if you meet any problem!
