### ISSUE TITLE
KaggleDataLoader failed to find the dataset

### ISSUE THREAD

**Issue by Jeffwan** [xlang-ai/OpenAgents#62]
![image](https://github.com/xlang-ai/OpenAgents/assets/4739316/6a833056-d566-4339-bd02-fea4d339d0b5)

```
openagents-backend-1   | 2023-11-03 00:58:45 | ERROR - ++-> KaggleDataLoader results(verbose=True callbacks=None callback_manager=None client=<class 'openai.api_resources.chat_completion.ChatCompletion'> model_name='gpt-3.5-turbo-16k' temperature=0.7 model_kwargs={} openai_api_key=None openai_api_base=None openai_organization=None request_timeout=None max_retries=6 streaming=True n=1 max_tokens=None stop=['[RESPONSE_BEGIN]', 'TOOL RESPONSE']):'str' object has no attribute 'items'
openagents-backend-1   | Traceback (most recent call last):
openagents-backend-1   |   File "/app/backend/api/chat_copilot.py", line 240, in run_kaggle_data_loader
openagents-backend-1   |     results = kaggle_data_loading_executor.run(
openagents-backend-1   |   File "/app/real_agents/data_agent/executors/kaggle_data_loading_executor.py", line 57, in run
openagents-backend-1   |     kaggle_output_info = self._search_kaggle(api, keywords, search_top_k)
openagents-backend-1   |   File "/app/real_agents/data_agent/executors/kaggle_data_loading_executor.py", line 87, in _search_kaggle
openagents-backend-1   |     datasets = api.dataset_list(max_size=20000, page=1, file_type="csv")[:search_top_k]
openagents-backend-1   |   File "/usr/local/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 1162, in dataset_list
openagents-backend-1   |     return [Dataset(d) for d in datasets_list_result]
openagents-backend-1   |   File "/usr/local/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 1162, in <listcomp>
openagents-backend-1   |     return [Dataset(d) for d in datasets_list_result]
openagents-backend-1   |   File "/usr/local/lib/python3.10/site-packages/kaggle/models/kaggle_models_extended.py", line 87, in __init__
openagents-backend-1   |     parsed_dict = {k: parse(v) for k, v in init_dict.items()}
openagents-backend-1   | AttributeError: 'str' object has no attribute 'items'
```

**Comment by BlankCheng** [comment]
Hi, it seems you are using the docker. May I know whether the kaggle user and key were set in the docker file? It seems the kaggle API can't search properly.

**Comment by Jeffwan** [comment]
@BlankCheng My bad, I kind of skip the Kaggle credential configuration in the process and that is the root cause. Once I set the environment, the problem is gone. Thank your for the insight.
