### ISSUE TITLE
run frontend error

### ISSUE THREAD

**Issue by SovereignRemedy** [xlang-ai/OpenAgents#74]

**Comment by SovereignRemedy** [comment]
`(base) ➜  frontend git:(main) npm run dev


> ai-chatbot-starter@0.1.0 dev
> next dev

(node:40412) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:40413) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
event - compiled client and server successfully in 1255 ms (273 modules)
wait  - compiling...
event - compiled successfully in 134 ms (235 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 6.8s (21003 modules)
error - TypeError: Cannot read properties of undefined (reading 'includes')
    at get platform [as platform] (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4222:23)
    at new KeyboardManager (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4202:35)
    at <static_initializer> (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4369:29)
    at Object.defineProperty.value (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:4342:22)
    at __w_pdfjs_require__ (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at Object.defineProperty.value (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:3737:14)
    at __w_pdfjs_require__ (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at Object.defineProperty.value (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:3562:15)
    at __w_pdfjs_require__ (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at Object.defineProperty.value (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:1119:27)
    at __w_pdfjs_require__ (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19477:41)
    at /Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19718:12
    at /Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19767:3
    at /Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:19770:12
    at webpackUniversalModuleDefinition (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:25:20)
    at Object.<anonymous> (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/pdfjs-dist/build/pdf.js:32:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/wangxin/go/src/OpenAgents/frontend/node_modules/react-pdf/dist/cjs/entry.js:27:37)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at react-pdf (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:1620:18)
    at __webpack_require__ (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/api/home/home.tsx:12:67)
    at __webpack_require__.a (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/api/home/home.tsx:1:21)
    at ./pages/api/home/home.tsx (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:733:1)
    at __webpack_require__ (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/api/home/index.ts:7:63)
    at __webpack_require__.a (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/api/home/index.ts:1:21)
    at ./pages/api/home/index.ts (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:744:1)
    at __webpack_require__ (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:7:67)
    at __webpack_require__.a (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/index.tsx:1:21)
    at ./pages/index.tsx (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:755:1)
    at __webpack_require__ (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:1806:39)
    at /Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:1807:28
    at Object.<anonymous> (/Users/wangxin/go/src/OpenAgents/frontend/.next/server/pages/index.js:1810:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  page: '/zh'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 1411 ms (21004 modules)`

同时还有一个前端报错 直接进入localhost:3000 会触发

**Comment by SovereignRemedy** [comment]
> env：macOS
> 
> flask run -p 8000
> 
> Dependencies for InstructorEmbedding not found. The auto selection feature of plugins agent will return random elements. 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 12/16 [00:01<00:00, 8.53it/s]/Users/wangxin/go/src/OpenAgents/real_agents/plugins_agent/plugins/DreamInterpreter/openapi.yaml and DreamInterpreter/paths/**init**.py do not match. Load the later. /Users/wangxin/go/src/OpenAgents/real_agents/plugins_agent/plugins/XWeather/openapi.yaml and XWeather/paths/**init**.py do not match. Load the later. 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 8.09it/s] Error: Failed to make the request WOLFRAM: HTTPSConnectionPool(host='www.wolframcdn.com', port=443): Max retries exceeded with url: /images/icons/Wolfram.png (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x15b3636d0>, 'Connection to [www.wolframcdn.com](http://www.wolframcdn.com) timed out. (connect timeout=None)')) Error: Failed to make the request DREAMINTERPRETER: 502 Server Error: Bad Gateway for url: https://dreamplugin.bgnetmobile.com/.well-known/logo.png
> 
> 全局代理似乎也不行，需要修改什么配置文件吗

这个等待很久超时之后是可以正常启动的，但是目前的阻塞点可能是在于前端无法启动

**Comment by WhiteWolf82** [comment]
> d/pdf.js:1

Try removing the installed node modules and pulling the code again. We've removed the pdfjs dependency to avoid such errors in https://github.com/xlang-ai/OpenAgents/pull/55

**Comment by BlankCheng** [comment]
Closed as inactive. Please feel free to reopen it if you encounter any problems!
