### ISSUE TITLE
frontend run error 

### ISSUE THREAD

**Issue by wolvever** [xlang-ai/OpenAgents#78]
Build and run frontend on windows.  Receive window is not defined error

npm: 10.2.0

> ai-chatbot-starter@0.1.0 dev
> next dev

(node:17772) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:25200) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
event - compiled client and server successfully in 5.9s (273 modules)
wait  - compiling...
event - compiled successfully in 411 ms (235 modules)
wait  - compiling / (client and server)...
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 23.9s (20964 modules)
warn  - Fast Refresh had to perform a full reload due to a runtime error.
error - ReferenceError: window is not defined
    at detect (C:\proj\llm\openagents\github\OpenAgents\frontend\node_modules\echarts\dist\echarts.js:123:54)
    at C:\proj\llm\openagents\github\OpenAgents\frontend\node_modules\echarts\dist\echarts.js:97:9
    at C:\proj\llm\openagents\github\OpenAgents\frontend\node_modules\echarts\dist\echarts.js:22:68
    at Object.<anonymous> (C:\proj\llm\openagents\github\OpenAgents\frontend\node_modules\echarts\dist\echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.echarts (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:1391:18)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Datatype/Chart/Echart.tsx:9:65)
    at ./components/Datatype/Chart/Echart.tsx (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:491:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Chat/ChatRichContentItem.tsx:15:91)
    at __webpack_require__.a (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/Chat/ChatRichContentItem.tsx:1:21)
    at ./components/Chat/ChatRichContentItem.tsx (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:293:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Chat/ChatMessage.tsx:16:94)
    at __webpack_require__.a (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/Chat/ChatMessage.tsx:1:21)
    at ./components/Chat/ChatMessage.tsx (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:282:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Chat/Chat.tsx:18:70)
    at __webpack_require__.a (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/Chat/Chat.tsx:1:21)
    at ./components/Chat/Chat.tsx (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:249:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/api/home/home.tsx:41:80)
    at __webpack_require__.a (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/api/home/home.tsx:1:21)
    at ./pages/api/home/home.tsx (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:722:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/api/home/index.ts:7:63)
    at __webpack_require__.a (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/api/home/index.ts:1:21)
    at ./pages/api/home/index.ts (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:733:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:7:67)
    at __webpack_require__.a (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/index.tsx:1:21)
    at ./pages/index.tsx (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:744:1)
    at __webpack_require__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:1764:39)
    at C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:1765:28
    at Object.<anonymous> (C:\proj\llm\openagents\github\OpenAgents\frontend\.next\server\pages\index.js:1768:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
  page: '/'
}

**Comment by BlankCheng** [comment]
Hi, sorry we haven't thorough test on windows yet. Could you try the docker deployment because it is os-agnostic? Or you might check the node and npm versions. The node 18.7.0, npm 8.15.0 or node 21.0.0 + npm 10.2.0 pair work for now.

**Comment by alena-m** [comment]
I have the same problem with macos, npm 10.2.3, node 21.2.0.

**Comment by BlankCheng** [comment]
Btw, it seems to be a known issue for node 21.0, please refer to this issue https://github.com/apache/echarts/issues/19233

**Comment by BlankCheng** [comment]
Please refer to #42 that solves this issue by down-grading npm and node.
