### ISSUE TITLE
Error: Could not find kaggle.json

### ISSUE THREAD

**Issue by alena-m** [xlang-ai/OpenAgents#94]
Hi,
I can't run backend. The command `flask run -p 8000` failed with the error:
`OSError: Could not find kaggle.json. Make sure it's located in /Users/XXX/.kaggle. Or use the environment method.`

Do I have to create a Kaggle account to use OpenAgents?

```
Traceback (most recent call last):
  File "/Users/XXX/miniconda3/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/XXX/path/OpenAgents/backend/__init__.py", line 4, in <module>
    from backend.api import (
  File "/Users/XXX/path/OpenAgents/backend/api/chat_copilot.py", line 5, in <module>
    from backend.api.file import _get_file_path_from_node
  File "/Users/XXX/path/OpenAgents/backend/api/file.py", line 8, in <module>
    from backend.main import (
  File "/Users/XXX/path/OpenAgents/backend/main.py", line 6, in <module>
    from backend.kernel_publisher import start_kernel_publisher
  File "/Users/XXX/path/OpenAgents/backend/kernel_publisher.py", line 4, in <module>
    from backend.utils.utils import logger
  File "/Users/XXX/path/OpenAgents/backend/utils/utils.py", line 21, in <module>
    from real_agents.data_agent import (
  File "/Users/XXX/path/OpenAgents/real_agents/data_agent/__init__.py", line 10, in <module>
    from real_agents.data_agent.executors.kaggle_data_loading_executor import KaggleDataLoadingExecutor
  File "/Users/XXX/path/OpenAgents/real_agents/data_agent/executors/kaggle_data_loading_executor.py", line 10, in <module>
    from kaggle.api.kaggle_api_extended import KaggleApi
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/kaggle/api/kaggle_api_extended.py", line 403, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /Users/XXX/.kaggle. Or use the environment method.



```

**Comment by Enogh** [comment]
When you sign up to Kaggle and request an API key, you will receive a json file. Can you try putting it in the specified folder?

**Comment by Timothyxxx** [comment]
Agree, and we mentioned that in the guidance, we will further work on make installation easier
